name = "rent"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "RENT"
database_name = "rent"
database_id = "65a5ded3-ffd8-4627-8ea4-9d8ced480b93"

# Cleanup expired contracts, guest accounts, and unpaid orders daily at 00:00 UTC
[triggers]
crons = ["0 0 * * *"]
