/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0.
 * Noncommercial use, modification, and distribution are permitted.
 * Keep this notice and the LICENSE file with all copies and modified versions. */

// A small, dependency-free PDF writer for the receipt attachment. Cloudflare
// Workers do not provide a filesystem or a Node PDF runtime, so this keeps the
// document deliberately within the standard PDF fonts and primitives.

export interface ReceiptPdfData {
  companyName: string
  companyAbn?: string
  companyEmail?: string
  companyPhone?: string
  companyAddress?: string
  customerName: string
  customerEmail: string
  customerPhone?: string
  orderNumber: string
  contractNumber?: string
  documentNumber: string
  invoiceNumber?: string
  issuedAt: string
  paidAt?: string
  paymentMethod: string
  transactionId?: string
  deviceName: string
  startDate?: string
  endDate?: string
  rentalPeriod?: number
  subtotal: number
  gstAmount: number
  depositAmount: number
  processingFee: number
  discountAmount: number
  totalAmount: number
  currency?: string
  documentId?: string
  template?: Partial<ReceiptPdfTemplate>
}

export interface ReceiptPdfTemplate {
  title: string
  abnLabel: string
  documentNumberLabel: string
  issuedLabel: string
  billedToLabel: string
  rentalOrderLabel: string
  contractLabel: string
  paymentLabel: string
  paidLabel: string
  descriptionLabel: string
  amountLabel: string
  gstLabel: string
  depositLabel: string
  processingFeeLabel: string
  discountLabel: string
  totalLabel: string
  paymentReferenceLabel: string
  thankYouText: string
  recordNote: string
  questionsLabel: string
  generatedByText: string
}

export const DEFAULT_RECEIPT_PDF_TEMPLATE: ReceiptPdfTemplate = {
  title: 'TAX INVOICE',
  abnLabel: 'ABN',
  documentNumberLabel: 'INVOICE NO.',
  issuedLabel: 'Issued',
  billedToLabel: 'BILLED TO',
  rentalOrderLabel: 'RENTAL ORDER',
  contractLabel: 'Contract',
  paymentLabel: 'Payment',
  paidLabel: 'Paid',
  descriptionLabel: 'DESCRIPTION',
  amountLabel: 'AMOUNT (AUD)',
  gstLabel: 'GST',
  depositLabel: 'Refundable security deposit',
  processingFeeLabel: 'Payment processing fee',
  discountLabel: 'Discount',
  totalLabel: 'TOTAL PAID',
  paymentReferenceLabel: 'Payment reference',
  thankYouText: 'Thank you for choosing our rental service.',
  recordNote: 'This document records the payment received for the rental order.',
  questionsLabel: 'Questions?',
  generatedByText: 'Generated by the rental management system',
}

const PAGE_WIDTH = 595
const PAGE_HEIGHT = 842
const encoder = new TextEncoder()

function ascii(value: unknown, fallback = '-'): string {
  const cleaned = String(value ?? '').replace(/[^\x20-\x7e]/g, '').trim()
  return cleaned || fallback
}

function displayText(value: unknown, max = 72, fallback = '-'): string {
  const text = ascii(value, fallback)
  return text.length > max ? `${text.slice(0, Math.max(1, max - 3))}...` : text
}

function pdfLiteral(value: unknown, max = 72, fallback = '-'): string {
  const text = displayText(value, max, fallback)
  return `(${text.replace(/\\/g, '\\\\').replace(/[()]/g, char => `\\${char}`)})`
}

function money(value: number, currency = 'AUD'): string {
  return `${ascii(currency, 'AUD')} ${Number(value || 0).toFixed(2)}`
}

function text(lines: string[], x: number, y: number, value: unknown, size = 10, font = 'F1', color = '0.12 0.16 0.22') {
  lines.push(`${color} rg BT /${font} ${size} Tf ${x} ${y} Td ${pdfLiteral(value)} Tj ET`)
}

function line(lines: string[], x1: number, y1: number, x2: number, y2: number, color = '0.86 0.88 0.91', width = 1) {
  lines.push(`${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S`)
}

function rect(lines: string[], x: number, y: number, width: number, height: number, color: string) {
  lines.push(`${color} rg ${x} ${y} ${width} ${height} re f`)
}

function concatBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0)
  const output = new Uint8Array(total)
  let offset = 0
  for (const part of parts) { output.set(part, offset); offset += part.length }
  return output
}

function makePdf(objects: string[]): Uint8Array {
  const parts: Uint8Array[] = [encoder.encode('%PDF-1.4\n')]
  const offsets = [0]
  let offset = parts[0].length
  for (let index = 0; index < objects.length; index++) {
    const bytes = encoder.encode(`${index + 1} 0 obj\n${objects[index]}\nendobj\n`)
    offsets.push(offset)
    parts.push(bytes)
    offset += bytes.length
  }
  const xrefOffset = offset
  const xref = [`xref`, `0 ${objects.length + 1}`, `0000000000 65535 f `]
  for (let index = 1; index < offsets.length; index++) xref.push(`${String(offsets[index]).padStart(10, '0')} 00000 n `)
  parts.push(encoder.encode(`${xref.join('\n')}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info ${objects.length} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`))
  return concatBytes(parts)
}

export function buildReceiptPdf(data: ReceiptPdfData): Uint8Array {
  const currency = ascii(data.currency, 'AUD')
  const template = { ...DEFAULT_RECEIPT_PDF_TEMPLATE, ...(data.template || {}) }
  const lines: string[] = []
  rect(lines, 0, 720, PAGE_WIDTH, 122, '0.08 0.11 0.16')
  rect(lines, 0, 720, 8, 122, '0.95 0.55 0.18')
  text(lines, 42, 800, ascii(data.companyName, 'PC Rental'), 19, 'F2', '1 1 1')
  const companyMeta = [displayText(data.companyAddress, 70, ''), data.companyPhone ? displayText(data.companyPhone, 24) : '', data.companyAbn ? `${template.abnLabel} ${displayText(data.companyAbn, 20)}` : ''].filter(Boolean).join(' | ')
  text(lines, 42, 778, companyMeta, 8.5, 'F1', '0.78 0.82 0.87')
  text(lines, 42, 748, template.title, 22, 'F2', '1 1 1')
  text(lines, 395, 797, template.documentNumberLabel, 8, 'F2', '0.95 0.55 0.18')
  text(lines, 395, 780, data.documentNumber, 12, 'F2', '1 1 1')
  text(lines, 395, 758, `${template.issuedLabel} ${displayText(data.issuedAt, 28)}`, 8.5, 'F1', '0.78 0.82 0.87')

  text(lines, 42, 685, template.billedToLabel, 8, 'F2', '0.95 0.55 0.18')
  text(lines, 42, 663, ascii(data.customerName, 'Customer'), 12, 'F2')
  text(lines, 42, 645, data.customerEmail, 9)
  text(lines, 42, 630, data.customerPhone, 9)
  text(lines, 300, 685, template.rentalOrderLabel, 8, 'F2', '0.95 0.55 0.18')
  text(lines, 300, 663, data.orderNumber, 12, 'F2')
  text(lines, 300, 645, `${template.contractLabel}: ${displayText(data.contractNumber)}`, 9)
  text(lines, 300, 630, `${template.paymentLabel}: ${displayText(data.paymentMethod, 28)}`, 9)
  text(lines, 300, 615, `${template.paidLabel}: ${displayText(data.paidAt || data.issuedAt, 28)}`, 9)
  line(lines, 42, 590, 553, 590, '0.75 0.78 0.82', 1.2)

  text(lines, 42, 568, template.descriptionLabel, 8, 'F2', '0.34 0.39 0.46')
  text(lines, 400, 568, template.amountLabel, 8, 'F2', '0.34 0.39 0.46')
  line(lines, 42, 555, 553, 555)
  text(lines, 42, 531, ascii(data.deviceName, 'Rental device'), 10, 'F2')
  text(lines, 42, 515, `${displayText(data.startDate)} to ${displayText(data.endDate)}${data.rentalPeriod ? ` - ${data.rentalPeriod} days` : ''}`, 8.5, 'F1', '0.38 0.43 0.49')
  text(lines, 400, 531, money(data.subtotal, currency), 10, 'F2')
  let rowY = 480
  const row = (label: string, amount: number, negative = false) => {
    if (!amount) return
    text(lines, 42, rowY, label, 9)
    text(lines, 400, rowY, `${negative ? '-' : ''}${money(Math.abs(amount), currency)}`, 9)
    rowY -= 24
  }
  row(template.gstLabel, data.gstAmount)
  row(template.depositLabel, data.depositAmount)
  row(template.processingFeeLabel, data.processingFee)
  row(template.discountLabel, data.discountAmount, true)
  line(lines, 42, rowY + 6, 553, rowY + 6)
  text(lines, 300, rowY - 22, template.totalLabel, 11, 'F2')
  text(lines, 400, rowY - 22, money(data.totalAmount, currency), 13, 'F2', '0.95 0.42 0.08')

  const paymentRef = data.transactionId ? `${template.paymentReferenceLabel}: ${displayText(data.transactionId, 48)}` : 'Payment completed successfully.'
  text(lines, 42, 245, paymentRef, 8.5, 'F1', '0.38 0.43 0.49')
  text(lines, 42, 222, template.thankYouText, 10, 'F2')
  text(lines, 42, 204, template.recordNote, 8.5, 'F1', '0.38 0.43 0.49')
  line(lines, 42, 172, 553, 172)
  text(lines, 42, 148, data.companyEmail ? `${template.questionsLabel} ${displayText(data.companyEmail, 70)}` : 'Please contact us if you have any questions.', 8.5, 'F1', '0.38 0.43 0.49')
  text(lines, 42, 116, `Document ID: ${displayText(data.documentId, 70)}`, 7.5, 'F1', '0.55 0.59 0.64')
  text(lines, 42, 92, template.generatedByText, 7.5, 'F1', '0.55 0.59 0.64')

  const stream = lines.join('\n')
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${encoder.encode(stream).length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    `<< /Producer ${pdfLiteral('PC Rental')} /Title ${pdfLiteral(template.title)} >>`,
  ]
  return makePdf(objects)
}

export function bytesToBase64(bytes: Uint8Array): string {
  let output = ''
  const chunkSize = 0x8000
  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    output += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize))
  }
  return btoa(output)
}
