ALTER TABLE users ADD COLUMN user_agreement_accepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN user_agreement_version TEXT;
ALTER TABLE users ADD COLUMN user_agreement_accepted_at TEXT;
ALTER TABLE users ADD COLUMN user_agreement_accepted_ip TEXT;
ALTER TABLE users ADD COLUMN service_terms_accepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN service_terms_version TEXT;
ALTER TABLE users ADD COLUMN service_terms_accepted_at TEXT;
ALTER TABLE users ADD COLUMN service_terms_accepted_ip TEXT;
ALTER TABLE users ADD COLUMN privacy_policy_accepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN privacy_policy_version TEXT;
ALTER TABLE users ADD COLUMN privacy_policy_accepted_at TEXT;
ALTER TABLE users ADD COLUMN privacy_policy_accepted_ip TEXT;
ALTER TABLE users ADD COLUMN refund_policy_accepted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN refund_policy_version TEXT;
ALTER TABLE users ADD COLUMN refund_policy_accepted_at TEXT;
ALTER TABLE users ADD COLUMN refund_policy_accepted_ip TEXT;
