/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0. */

import type { Context } from 'hono'
import { buildLayout, ensureNotificationsTable, getContractByOrderId, getOrderById, sanitizePlainText } from '../../site'

export async function renderGuestAccount(c: Context, user: any, message = '', type: 'error' | 'success' = 'error', upgradeOnly = false) {
  const order = user.guestOrderId ? await getOrderById(c, user.guestOrderId) : null
  const contract = order ? await getContractByOrderId(c, order.id) : null
  await ensureNotificationsTable(c)
  const announcementPageSize = 10
  const announcementCount = Number(((await c.env.RENT.prepare("SELECT COUNT(*) AS count FROM notifications WHERE recipient_id = ? AND type = 'announcement' AND deleted_at IS NULL").bind(user.id).first()) as any)?.count || 0)
  const announcementPageCount = Math.max(1, Math.ceil(announcementCount / announcementPageSize))
  const requestedAnnouncementPage = Math.max(1, Number(c.req.query('announcementPage') || 1) || 1)
  const announcementPage = Math.min(requestedAnnouncementPage, announcementPageCount)
  const announcements = (await c.env.RENT.prepare("SELECT id, title, message, created_at FROM notifications WHERE recipient_id = ? AND type = 'announcement' AND deleted_at IS NULL ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(user.id, announcementPageSize, (announcementPage - 1) * announcementPageSize).all()).results || []
  const upgradeForm = `<section class="panel"><div class="section-title"><h3>升级正式账户</h3><span class="section-note">保留当前邮箱</span></div><p>设置新密码后将解除访客限制，账户不会在租期结束时失效。</p><form method="post" action="/customer/guest/upgrade"><div class="form-group"><label class="form-label" for="newPassword">新密码</label><input class="form-control" id="newPassword" name="newPassword" type="password" minlength="8" pattern="(?=.*[A-Za-z])(?=.*[0-9])(?=.*[^A-Za-z0-9\\s])\\S{8,}" autocomplete="new-password" required><small class="form-text">至少 8 位，包含字母、数字和符号。</small></div><div class="form-group"><label class="form-label" for="confirmPassword">确认新密码</label><input class="form-control" id="confirmPassword" name="confirmPassword" type="password" minlength="8" autocomplete="new-password" required></div><p class="form-text">升级账户即表示您已阅读并同意<a href="/user-terms" target="_blank" rel="noopener">用户协议</a>、<a href="/service-terms" target="_blank" rel="noopener">服务条款</a>和<a href="/privacy" target="_blank" rel="noopener">隐私政策</a>。</p><button class="button" type="submit">升级为正式账户</button></form></section>`
  const body = upgradeOnly ? `<div class="page-header"><div><p class="section-code">ACCOUNT UPGRADE</p><h2>升级正式账户</h2><p>保留当前邮箱，设置密码后即可继续使用完整账户功能。</p></div><a class="button button-secondary" href="/customer/guest">返回访客中心</a></div>${message ? `<div class="page-notification page-notification--${type === 'success' ? 'success' : 'error'}">${message}</div>` : ''}${upgradeForm}` : `<div class="entity-header guest-account-header"><div class="identity-strip mono"><span>GUEST ACCESS</span><span>有效至 ${user.guestExpiresAt || order?.endDate || '租期结束'}</span></div><div class="entity-heading"><div><p class="section-code">TEMPORARY ACCOUNT</p><h2>访客合同中心</h2><p>此账户仅用于本次租赁的付款、合同和收据。</p></div><span class="badge badge-warning">访客账户</span></div></div>
  ${message ? `<div class="page-notification page-notification--${type === 'success' ? 'success' : 'error'}">${message}</div>` : ''}
  <section class="panel guest-announcements"><div class="section-title"><h3>历史通告</h3><a class="link-button" href="/notifications">通知中心 →</a></div>${announcements.length ? `<div class="notification-list">${announcements.map((item: any) => `<a class="dashboard-announcement" href="/notifications/${encodeURIComponent(item.id)}"><strong>${sanitizePlainText(item.title, 120)}</strong><span>${sanitizePlainText(item.created_at, 80)}</span><p>${sanitizePlainText(item.message, 300)}</p></a>`).join('')}</div>${announcementPageCount > 1 ? `<nav class="pagination" aria-label="历史通告分页">${Array.from({ length: announcementPageCount }, (_, index) => `<a class="button button-sm ${index + 1 === announcementPage ? 'button-primary' : 'button-secondary'}" href="/customer/guest?announcementPage=${index + 1}">${index + 1}</a>`).join('')}</nav>` : ''}` : '<p class="empty-state">暂无历史通告</p>'}</section>
  <div class="grid grid-2 guest-workspace"><section class="panel"><div class="section-title"><h3>本次租赁</h3><span class="mono">${order?.orderNo || '付款后生成'}</span></div>${order ? `<p>${order.startDate} 至 ${order.endDate}</p><div class="record-actions"><a class="button" href="/customer/orders/${order.id}">查看订单与付款</a>${contract ? `<a class="button button-secondary" href="/customer/orders/${order.id}">查看订单详情</a>` : ''}<a class="button button-secondary" href="/orders/${order.id}/invoice">合同与收据</a></div>` : '<p>未找到关联订单，请联系工作人员。</p>'}</section><section class="panel"><div class="section-title"><h3>升级正式账户</h3><span class="section-note">保留当前邮箱</span></div><p>升级后可使用完整账户功能，账户也不会在本次租期结束后失效。</p><a class="button button-primary" href="/customer/guest/upgrade">前往升级账户</a></section></div>`
  return buildLayout('访客合同中心', body, user)
}
