/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0.
 * Noncommercial use, modification, and distribution are permitted.
 * Keep this notice and the LICENSE file with all copies and modified versions. */

export function renderSquareGiftCardPaymentBox(options: { configUrl: string; paymentUrl: string; returnUrl: string; buttonLabel: string; domId: string }): string {
  const configJson = JSON.stringify(options).replace(/</g, '\\u003c')
  return `<div class="square-gift-card-box" id="${options.domId}"><p class="form-text">Square 礼品卡支付由 Square 安全处理，本站不会保存礼品卡号码。</p><div data-square-input></div><button type="button" class="button button-primary" data-square-pay>加载礼品卡支付</button><p class="form-text" data-square-status role="status"></p></div><script>(()=>{const root=document.getElementById(${JSON.stringify(options.domId)});if(!root)return;const cfg=${configJson};const button=root.querySelector('[data-square-pay]');const inputSelector='#'+${JSON.stringify(options.domId)}+' [data-square-input]';const status=root.querySelector('[data-square-status]');let giftCard;const setStatus=(text)=>{status.textContent=text};const loadSdk=(env)=>new Promise((resolve,reject)=>{if(window.Square)return resolve();const script=document.createElement('script');script.src=env==='production'?'https://web.squarecdn.com/v1/square.js':'https://sandbox.web.squarecdn.com/v1/square.js';script.onload=resolve;script.onerror=()=>reject(new Error('Square 支付组件加载失败'));document.head.appendChild(script)});button.addEventListener('click',async()=>{button.disabled=true;setStatus('正在加载 Square 礼品卡组件…');try{const response=await fetch(cfg.configUrl,{headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||'无法读取 Square 配置');if(data.alreadyPaid){location.href=cfg.returnUrl;return}await loadSdk(data.environment);const payments=window.Square.payments(data.applicationId,data.locationId);giftCard=await payments.giftCard();await giftCard.attach(inputSelector);button.textContent=${JSON.stringify(options.buttonLabel)};button.disabled=false;button.onclick=async()=>{button.disabled=true;setStatus('正在验证礼品卡并提交付款…');try{const tokenResult=await giftCard.tokenize();if(tokenResult.status!=='OK')throw new Error(tokenResult.errors?.map((item)=>item.message).join('；')||'礼品卡验证失败');const paymentResponse=await fetch(cfg.paymentUrl,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({sourceId:tokenResult.token})});const payment=await paymentResponse.json();if(!paymentResponse.ok)throw new Error(payment.error||'Square 礼品卡付款失败');location.href=cfg.returnUrl}catch(error){setStatus(error.message||'Square 礼品卡付款失败');button.disabled=false}}}catch(error){setStatus(error.message||'Square 礼品卡支付不可用');button.disabled=false}})})();</script>`
}
