import { buildLayout, sanitizePlainText } from '../../site'

const esc = (value: unknown, limit = 500) => sanitizePlainText(value, limit).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
const labels: Record<string, string> = { PAID_ORDER_WITHOUT_PAYMENT: '已付款但缺少结算记录', ACTIVE_ORDER_WITHOUT_HANDOVER: '租赁中但缺少交接记录' }

export function renderAdminAnomalousOrders(user: any, reviews: any[] = []) {
  const pending = reviews.filter(item => item.status === 'PENDING')
  const rows = reviews.map(item => `<tr><td><a class="mono" href="/admin/orders/${encodeURIComponent(item.order_id)}">${esc(item.order_no || item.order_id, 80)}</a><small>${esc(item.customer_name || item.customer_email || '-', 120)}</small></td><td><strong>${esc(labels[item.anomaly_type] || item.anomaly_type, 120)}</strong><small>发现于：${esc(item.detected_at, 80)}</small></td><td><span class="badge ${item.status === 'PENDING' ? 'badge-warning' : item.status === 'RESTORED' ? 'badge-success' : 'badge-neutral'}">${item.status === 'PENDING' ? '待审核 / 已暂停' : item.status === 'RESTORED' ? '已恢复' : '确认暂停'}</span><small>原状态：${esc(item.original_status, 40)}</small></td><td>${item.status === 'PENDING' ? `<form method="post" action="/admin/finance/anomalous-orders/${encodeURIComponent(item.id)}" style="display:grid;gap:8px;min-width:220px"><textarea class="form-control" name="note" maxlength="1000" required placeholder="审核说明（必填）"></textarea><div class="record-actions"><button class="button button-sm button-primary" name="decision" value="restore" type="submit">恢复订单</button><button class="button button-sm button-secondary" name="decision" value="confirm" type="submit">确认继续暂停</button></div></form>` : `<small>${esc(item.review_note || '-', 1000)}<br>审核：${esc(item.reviewer_name || item.reviewed_by || '-', 100)}</small>`}</td></tr>`).join('')
  const body = `<div class="page-header"><div><p class="section-code">FINANCE / ANOMALOUS ORDERS</p><h2>异常订单审核</h2><p>系统检测到高风险订单后会先暂停，需管理员审核后恢复或确认继续暂停。</p></div><a class="button button-secondary" href="/admin/finance">返回财务管理</a></div><div class="stats-grid"><div class="stat-card warning"><h3>待审核异常订单</h3><div class="value">${pending.length}</div></div><div class="stat-card"><h3>审核历史</h3><div class="value">${reviews.length}</div></div></div><section class="panel"><div class="section-title"><h3>审核队列</h3><span class="section-note">自动暂停仅用于高置信度数据异常</span></div>${rows ? `<div class="table-wrapper"><table><thead><tr><th>订单 / 客户</th><th>异常原因</th><th>状态</th><th>审核处理</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty-state"><h3>暂无异常订单</h3><p>系统定时检测到异常时会自动加入此队列。</p></div>'}</section>`
  return buildLayout('异常订单审核 - 电脑租赁管理系统', body, user)
}
