import { buildLayout, sanitizePlainText } from '../../site'

export function renderAdminDeviceControl(user: any, device: any, commands: any[] = []) {
  if (!device) return buildLayout('设备远程控制', '<div class="panel"><h2>设备未找到</h2></div>', user)
  const esc = (value: unknown) => sanitizePlainText(value, 500).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const labels: Record<string, string> = { SYNC: '立即同步', REFRESH_DEVICE_INFO: '刷新设备信息', CHECK_UPDATE: '检查客户端更新', PAUSE_RENTAL: '暂停设备', RESUME_RENTAL: '恢复设备', SHOW_MESSAGE: '发送设备通知' }
  const rows = commands.length ? commands.map(command => `<tr><td class="mono">${esc(command.created_at)}</td><td>${labels[command.command_type] || esc(command.command_type)}</td><td><span class="badge ${command.status === 'SUCCEEDED' ? 'badge-success' : command.status === 'FAILED' || command.status === 'EXPIRED' ? 'badge-danger' : 'badge-warning'}">${esc(command.status)}</span></td><td>${esc(command.result_message || '等待客户端执行')}</td></tr>`).join('') : '<tr><td colspan="4" class="empty-state">暂无远程命令记录</td></tr>'
  const action = (type: string, text: string, className = 'button-secondary') => `<button class="button ${className}" name="commandType" value="${type}" type="submit">${text}</button>`
  const body = `<div class="page-header"><div><p class="section-code">REMOTE CONTROL</p><h2>${esc(device.name)}</h2><p>${esc(device.model)} · ${esc(device.serialNumber || device.serial_number || '无序列号')}</p></div><div class="record-actions"><a class="button button-secondary" href="/admin/devices/${encodeURIComponent(device.id)}/edit">编辑设备</a><a class="button button-secondary" href="/admin/device-agent-bindings">绑定设备</a></div></div><div class="panel"><h3>远程操作</h3><p class="form-text">命令会进入队列，由 Windows 客户端下一次心跳时领取并执行。</p><form method="post" action="/admin/devices/${encodeURIComponent(device.id)}/commands"><div class="record-actions">${action('SYNC', '立即同步')}${action('REFRESH_DEVICE_INFO', '刷新设备信息')}${action('CHECK_UPDATE', '检查客户端更新')}${action('PAUSE_RENTAL', '暂停设备', 'button-warning')}${action('RESUME_RENTAL', '恢复设备', 'button-success')}</div><div class="grid grid-2" style="margin-top:14px"><input class="form-control" name="title" maxlength="120" placeholder="通知标题"><input class="form-control" name="message" maxlength="500" placeholder="通知内容"></div>${action('SHOW_MESSAGE', '发送设备通知')}</form></div><div class="panel"><div class="section-title"><h3>最近 20 条远程命令</h3><span class="section-note">操作时间 · 操作类型 · 执行状态 · 客户端返回结果</span></div><div class="table-wrapper"><table><thead><tr><th>操作时间</th><th>操作类型</th><th>执行状态</th><th>客户端返回结果</th></tr></thead><tbody>${rows}</tbody></table></div></div>`
  return buildLayout(`设备远程控制 - ${device.name}`, body, user)
}
