import { buildLayout, getDevices, sanitizePlainText } from '../../site'

export async function renderAdminDeviceAgentBindings(c: any, user: any) {
  const devices = await getDevices(c)
  const now = Date.now()
  const esc = (value: unknown) => sanitizePlainText(String(value ?? '—'), 200)
  const status = (device: any) => device.agent_status === 'online' ? '在线' : device.agent_token_hash ? '已绑定' : '未绑定'
  const onlineCount = devices.filter((device: any) => device.agent_status === 'online').length
  const boundCount = devices.filter((device: any) => device.agent_token_hash).length
  const pendingCount = devices.filter((device: any) => device.agent_setup_code_expires_at && new Date(device.agent_setup_code_expires_at).getTime() > now).length
  const rows = devices.map((device: any) => {
    const expiry = device.agent_setup_code_expires_at ? new Date(device.agent_setup_code_expires_at).getTime() : 0
    const codeStatus = expiry > now ? '待输入' : device.agent_setup_code_hash ? '已过期' : '—'
    const statusClass = device.agent_status === 'online' ? 'badge-success' : device.agent_token_hash ? 'badge-primary' : 'badge-neutral'
    return `<tr><td><strong>${esc(device.name)}</strong><br><small class="mono">${esc(device.model)}</small></td><td class="mono">网站：${esc(device.serialNumber || device.serial_number)}<br>本机：${esc(device.agent_detected_serial || '未上报')}</td><td><span class="badge ${statusClass}">${status(device)}</span><br><small class="mono">${esc(device.agent_version || '版本未知')}</small></td><td>${esc(device.agent_registered_at)}</td><td>${codeStatus}</td><td><div class="record-actions record-actions--compact"><a class="button button-sm button-secondary" href="/admin/devices/${encodeURIComponent(device.id)}/agent-install">${device.agent_setup_code_hash ? '重新生成访问码' : '生成访问码'}</a><a class="button button-sm button-secondary" href="/admin/devices/${encodeURIComponent(device.id)}/edit">查看设备</a>${device.agent_token_hash ? `<form method="post" action="/admin/device-agent-bindings/${encodeURIComponent(device.id)}/unbind" style="display:inline" data-site-confirm="确认解绑此设备？解绑后 EXE 才能卸载或删除。"><button class="button button-sm button-danger" type="submit">解绑</button></form>` : ''}</div></td></tr>`
  }).join('')
  const body = `<div class="page-header"><div><p class="section-code">WINDOWS AGENT / CONTROL DESK</p><h2>绑定设备</h2><p>从这里下载客户端、生成一次性访问码，并处理设备解绑。访问码有效期为 15 分钟，成功绑定后立即失效。</p></div><div class="record-actions"><a class="button button-primary" href="/downloads/RentDeviceAgent-Setup.exe">下载 Windows 客户端</a><a class="button button-secondary" href="/admin/devices">设备管理</a></div></div><div class="grid grid-3" style="margin-bottom:20px"><div class="panel"><span class="section-note">在线设备</span><strong style="display:block;font-size:30px;margin-top:8px">${onlineCount}</strong><small class="section-note">正在发送心跳</small></div><div class="panel"><span class="section-note">已绑定</span><strong style="display:block;font-size:30px;margin-top:8px">${boundCount}</strong><small class="section-note">可远程读取状态</small></div><div class="panel"><span class="section-note">待输入访问码</span><strong style="display:block;font-size:30px;margin-top:8px">${pendingCount}</strong><small class="section-note">15 分钟内有效</small></div></div><div class="panel"><div class="section-title"><div><p class="section-code">QUICK ACTIONS</p><h3>软件快捷操作</h3><p>先下载客户端，再为对应设备生成访问码；客户端首次运行时输入访问码即可绑定。</p></div><a class="button button-sm button-secondary" href="/admin/device-agent-bindings">刷新状态</a></div><div class="record-actions"><a class="button button-primary" href="/downloads/RentDeviceAgent-Setup.exe">下载最新安装程序</a><a class="button button-secondary" href="https://github.com/aaoqqqdd/rent-app/releases" target="_blank" rel="noopener">查看版本更新</a><a class="button button-secondary" href="/admin/devices">选择设备</a></div></div><div class="panel"><div class="section-title"><div><p class="section-code">DEVICE ROSTER</p><h3>客户端设备</h3></div><span class="section-note">共 ${devices.length} 台设备</span></div><div class="table-wrapper"><table><thead><tr><th>设备</th><th>序列号</th><th>客户端状态</th><th>绑定时间</th><th>访问码</th><th>快捷操作</th></tr></thead><tbody>${rows || '<tr><td colspan="6">暂无设备。请先在设备管理中创建设备。</td></tr>'}</tbody></table></div></div>`
  return buildLayout('Windows 客户端绑定设备 - 电脑租赁管理系统', body, user)
}
