import { buildLayout } from '../../site'

export async function renderAdminEmailTemplates(c: any, user: any) {
  await c.env.RENT.prepare('CREATE TABLE IF NOT EXISTS email_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run()
  try { await c.env.RENT.prepare("ALTER TABLE email_templates ADD COLUMN format TEXT NOT NULL DEFAULT 'markdown'").run() } catch (_) {}
  // 内置模板的兜底植入（仅当迁移未跑、对应行缺失时生效）。正文为结构化 HTML，
  // 与 migrations/0118_richen_email_templates.sql 的范式一致；已存在的行不会被覆盖。
  const footer = '<hr style="border:0; border-top:1px solid #ddd; margin:24px 0;"><p style="font-size:12px; color:#888;">此邮件由系统自动发送，请勿直接回复。</p>'
  const sign = '<p><strong>{company_name}</strong><br>{company_email}</p>'
  const seed = (id: string, name: string, subject: string, body: string) =>
    c.env.RENT.prepare("INSERT OR IGNORE INTO email_templates (id, name, subject, body, format) VALUES (?, ?, ?, ?, 'html')").bind(id, name, subject, body)
  await c.env.RENT.batch([
    seed('email_verification', '验证邮箱', '请验证您的邮箱 - {company_name}',
      `<h2>验证您的邮箱</h2><p>您好 {customer_name}：</p><p>感谢您注册 <strong>{company_name}</strong>。请验证您的邮箱地址以完成账户激活。</p><h3>验证详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">邮箱地址</td><td style="padding:8px 0;"><strong>{customer_email}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">链接有效期</td><td style="padding:8px 0;">24 小时</td></tr></tbody></table><p>请点击以下链接验证您的邮箱地址：<br><a href="{verification_url}">{verification_url}</a></p><p>如需帮助，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`),
    seed('welcome_site', '欢迎邮件', '欢迎加入 {company_name}',
      `<h2>欢迎加入 {company_name}</h2><p>您好 {customer_name}：</p><p>欢迎使用 <strong>{company_name}</strong> 设备租赁服务。您的账户已创建成功。</p><h3>账户信息</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">账户姓名</td><td style="padding:8px 0;"><strong>{customer_name}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">登录邮箱</td><td style="padding:8px 0;">{customer_email}</td></tr></tbody></table><p>您现在可以浏览设备、在线下单并电子签署租赁合同。如需帮助，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`),
    seed('order_created', '订单已创建', '订单已创建 - {order_number}',
      `<h2>订单已创建</h2><p>您好 {customer_name}：</p><p>您的订单已成功创建。感谢您选择 <strong>{company_name}</strong>。</p><h3>订单详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">合同编号</td><td style="padding:8px 0;">{contract_number}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁期间</td><td style="padding:8px 0;">{start_date} 至 {end_date}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁时长</td><td style="padding:8px 0;">{rental_period}</td></tr><tr><td style="padding:8px 0; color:#666;">订单金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">押金</td><td style="padding:8px 0;">{deposit_amount}</td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在 <strong>{payment_due_date}</strong> 前完成付款并电子签署租赁合同。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('order_approved', '订单审核通过', '订单审核通过 - {order_number}',
      `<h2>订单审核通过</h2><p>您好 {customer_name}：</p><p>您的订单已通过审核。感谢您选择 <strong>{company_name}</strong>。</p><h3>订单详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">应付金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在 <strong>{payment_due_date}</strong> 前完成付款，逾期订单可能被自动取消。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('payment_reminder', '付款提醒', '付款提醒 - {order_number}',
      `<h2>付款提醒</h2><p>您好 {customer_name}：</p><p>我们注意到您的订单尚未完成付款。感谢您选择 <strong>{company_name}</strong>。</p><h3>待付款详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">待付金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在付款截止日 <strong>{payment_due_date}</strong> 前完成付款，以免订单被取消。如已完成付款或有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('pickup_reminder', '取件提醒', '取件提醒 - {order_number}',
      `<h2>取件提醒</h2><p>您好 {customer_name}：</p><p>您的设备已准备就绪，请按下方安排取件。感谢您选择 <strong>{company_name}</strong>。</p><h3>取件详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">取件日期</td><td style="padding:8px 0;"><strong>{pickup_date}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">取件地点</td><td style="padding:8px 0;">{pickup_location}</td></tr></tbody></table><p>取件时请当场检查设备外观与功能并确认无误。如需调整取件时间，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('return_confirmed', '归还确认', '设备归还确认 - {order_number}',
      `<h2>设备归还确认</h2><p>您好 {customer_name}：</p><p>我们已确认收到您归还的设备。感谢您选择 <strong>{company_name}</strong>。</p><h3>归还详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">归还日期</td><td style="padding:8px 0;">{return_date}</td></tr></tbody></table><p>我们将对设备进行验机。押金结算与退款结果将另行通知，通常在 10 个营业日内完成。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('password_reset', '密码重置', '重置您的登录密码 - {company_name}',
      `<h2>重置登录密码</h2><p>您好 {customer_name}：</p><p>我们收到了重置您账户密码的请求。若非本人操作，请忽略本邮件，您的密码不会被更改。</p><h3>重置详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">账户邮箱</td><td style="padding:8px 0;"><strong>{customer_email}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">链接有效期</td><td style="padding:8px 0;">24 小时</td></tr></tbody></table><p>请通过以下链接重置密码，链接过期后请重新申请：<br><a href="{reset_url}">{reset_url}</a></p><p>如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}<hr style="border:0; border-top:1px solid #ddd; margin:24px 0;"><p style="font-size:12px; color:#888;">此邮件由系统自动发送，请勿直接回复。如果您并未申请重置密码，请立即联系 {company_name}。</p>`),
    seed('agreement_update', '协议更新通知', '协议内容已更新 - {company_name}',
      `<h2>协议内容已更新</h2><p>您好 {customer_name}：</p><p>我们更新了以下协议内容，特此通知。感谢您选择 <strong>{company_name}</strong>。</p><h3>更新详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">更新内容</td><td style="padding:8px 0;"><strong>{changed_agreements}</strong></td></tr></tbody></table><p>最新版本已在我们网站的对应页面公布。继续使用服务即视为接受更新后的内容；如不同意，您可以联系我们并停止使用相关服务。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`)
  ])
  const rows = (await c.env.RENT.prepare('SELECT * FROM email_templates ORDER BY name').all()).results as any[]
  const pageSize = 10
  const requestedPage = Math.max(1, Number(new URL(c.req.url).searchParams.get('page') || 1) || 1)
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize))
  const page = Math.min(requestedPage, pageCount)
  const pageRows = rows.slice((page - 1) * pageSize, page * pageSize)
  const recipients = (await c.env.RENT.prepare("SELECT id, name, email FROM users WHERE role IN ('CUSTOMER','STAFF') AND status != 'inactive' ORDER BY name").all()).results as any[]
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const variables = '{customer_name}、{customer_email}、{order_number}、{contract_number}、{device_name}、{start_date}、{end_date}、{rental_period}、{pickup_date}、{pickup_location}、{return_date}、{return_location}、{total_amount}、{deposit_amount}、{refund_amount}、{payment_due_date}、{sign_url}、{verification_url}、{reset_url}、{company_name}、{company_email}'
  const variableIndex = `<details class="variable-index" open><summary>可用变量（${variables.split('、').length} 项）</summary><section class="contract-variable-group"><div class="variable-chip-list">${variables.split('、').map(variable => `<code>${variable}</code>`).join('')}</div></section></details>`
  const pagination = pageCount > 1 ? `<nav class="pagination" aria-label="邮件模板分页">${Array.from({ length: pageCount }, (_, i) => `<a class="button button-sm ${i + 1 === page ? 'button-primary' : 'button-secondary'}" href="/admin/email-templates?page=${i + 1}">${i + 1}</a>`).join('')}</nav>` : ''
  const body = `<div class="entity-header"><div class="identity-strip mono"><span>COMMUNICATION / NOTIFICATIONS</span><span>${rows.length} TEMPLATES</span></div><div class="entity-heading"><div><p class="section-code">MESSAGE LIBRARY</p><h2>通知模板</h2><p>管理站内通知、邮件和欢迎/验证类消息，发送时选择通知方式。</p></div></div></div>${variableIndex}<div class="panel"><div class="section-title"><h3>新建模板</h3><span class="section-note">管理员可创建自定义通知模板</span></div><form method="post" action="/admin/email-templates" class="form-grid"><div><label class="form-label">模板名称</label><input class="form-control" name="name" maxlength="80" required></div><div><label class="form-label">邮件主题</label><input class="form-control" name="subject" maxlength="200" required></div><div style="grid-column:1/-1"><label class="form-label">正文（HTML）</label><textarea class="form-control html-editor" name="body" rows="8" maxlength="10000" required></textarea></div><div style="grid-column:1/-1"><button class="button button-primary" type="submit">添加模板</button></div></form></div><div class="panel email-send-panel"><div class="section-title"><h3>发送通知</h3><span class="section-note">选择模板和发送目标，模板变量由系统自动填充</span></div><form method="post" action="/admin/email-templates/send" class="form-grid"><div><label class="form-label">选择模板</label><select class="form-control" name="templateId" required>${rows.map(row => `<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('')}</select></div><div><label class="form-label">发送方式</label><select class="form-control" name="channel" required><option value="site">仅站内通知</option><option value="email">仅邮件</option><option value="both">站内通知 + 邮件</option></select></div><div><label class="form-label">站内通知收件人</label><select class="form-control" name="recipientId"><option value="">不发送站内通知</option>${recipients.map(row => `<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.email)}</option>`).join('')}</select></div><div><label class="form-label">邮件收件邮箱</label><input class="form-control" type="email" name="to" placeholder="customer@example.com"></div><div class="form-note" style="grid-column:1/-1"><small class="form-text">客户姓名、邮箱和公司信息会根据收件人自动填充；未提供的数据将留空。</small></div><div style="grid-column:1/-1"><button class="button button-primary" type="submit">发送通知</button></div></form></div><div class="panel email-template-list">${pageRows.map(row => `<form method="post" action="/admin/email-templates/${esc(row.id)}" class="email-template-card"><div class="section-title"><h3>${esc(row.name)}</h3><span class="badge ${row.enabled ? 'badge-success' : 'badge-neutral'}">${row.enabled ? '启用' : '停用'}</span></div><label class="form-label">主题</label><input class="form-control" name="subject" value="${esc(row.subject)}" required><label class="form-label">正文（HTML）</label><textarea class="form-control html-editor" name="body" rows="8" required>${esc(row.body)}</textarea>${variableIndex}<button class="button button-primary" type="submit">保存模板</button></form>`).join('')}</div>${pagination}`
  const bodyWithoutSend = body.replace(/<div class="panel email-send-panel">[\s\S]*?<div class="panel email-template-list">/, '<div class="panel email-template-list">')
  const bodyWithFormat = bodyWithoutSend.replace(/正文<\/label>/g, '正文（HTML）<\/label>')
    .replace(/(<input class="form-control" name="subject" maxlength="200" required>)/, '$1<div><label class="form-label">主题色</label><input class="form-control" type="color" name="theme_color" value="#71818d"></div>')
    .replace(/(<input class="form-control" name="subject" value="\$\{esc\(row\.subject\)\}" required>)/g, '$1<label class="form-label">主题色</label><input class="form-control" type="color" name="theme_color" value="${esc(row.theme_color || (row.id.startsWith(\'custom_\') ? \'#71818d\' : \'#f0a35b\'))}">')
    .replace(/(<form method="post" action="\/admin\/email-templates" class="form-grid">)/, '$1')
    .replace(/(<form method="post" action="\/admin\/email-templates\/[^" ]+" class="email-template-card">)/g, '$1')
  const bodyWithCustomSend = bodyWithFormat
    .replace('name="templateId" required>', 'name="templateId" required><option value="custom">自定义通知</option>')
    .replace('</select></div><div><label class="form-label">发送方式', '</select></div><div class="custom-send-fields" hidden style="grid-column:1/-1"><label class="form-label">自定义标题</label><input class="form-control" name="subject" maxlength="200"><label class="form-label">自定义内容（HTML）</label><textarea class="form-control html-editor" name="body" rows="8" maxlength="20000"></textarea>${variableIndex}</div><div><label class="form-label">发送方式')
  const bodyWithDelete = bodyWithCustomSend.replace(/保存模板<\/button>/g, "保存模板</button><button class=\"button button-danger\" type=\"submit\" formmethod=\"post\" onclick=\"this.form.action += '/delete'; return confirm('确定删除这个模板吗？')\">删除模板</button>")
  const collapseScript = `<script>(()=>{document.querySelectorAll('.email-template-card').forEach(form=>{const heading=form.querySelector('.section-title');if(!heading)return;const fields=[...form.children].filter(el=>el!==heading);fields.forEach(el=>el.hidden=true);heading.style.cursor='pointer';heading.title='点击展开/收起';heading.addEventListener('click',()=>{fields.forEach(el=>el.hidden=!el.hidden)});});const form=document.querySelector('.email-send-panel form');const template=form?.querySelector('[name="templateId"]');const custom=form?.querySelector('.custom-send-fields');const channel=form?.querySelector('[name="channel"]');const recipient=form?.querySelector('[name="recipientId"]');const to=form?.querySelector('[name="to"]');const sync=()=>{const mode=channel?.value||'site';if(custom)custom.hidden=template?.value!=='custom';if(recipient?.closest('div'))recipient.closest('div').hidden=!['site','both'].includes(mode);if(to?.closest('div'))to.closest('div').hidden=!['email','both'].includes(mode);if(recipient)recipient.required=['site','both'].includes(mode);if(to)to.required=['email','both'].includes(mode)};template?.addEventListener('change',sync);channel?.addEventListener('change',sync);sync();})()</script>`
  return buildLayout('邮件通知模板 - 电脑租赁管理系统', bodyWithDelete + collapseScript, user)
}
