import { buildLayout } from '../../site'

export async function renderAdminEmailTemplates(c: any, user: any) {
  await c.env.RENT.prepare('CREATE TABLE IF NOT EXISTS email_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run()
  await c.env.RENT.batch([
    c.env.RENT.prepare("INSERT OR IGNORE INTO email_templates (id, name, subject, body) VALUES ('email_verification', '验证邮箱', '验证您的邮箱 - PC Rental', '您好 {customer_name}，请验证您的邮箱：{verification_url}')"),
    c.env.RENT.prepare("INSERT OR IGNORE INTO email_templates (id, name, subject, body) VALUES ('welcome_site', '欢迎来到网站', '欢迎来到 PC Rental', '欢迎您，{customer_name}！感谢您使用 PC Rental。')")
  ])
  const rows = (await c.env.RENT.prepare('SELECT * FROM email_templates ORDER BY name').all()).results as any[]
  const recipients = (await c.env.RENT.prepare("SELECT id, name, email FROM users WHERE role IN ('CUSTOMER','STAFF') AND status != 'inactive' ORDER BY name").all()).results as any[]
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const body = `<div class="entity-header"><div class="identity-strip mono"><span>COMMUNICATION / NOTIFICATIONS</span><span>${rows.length} TEMPLATES</span></div><div class="entity-heading"><div><p class="section-code">MESSAGE LIBRARY</p><h2>通知模板</h2><p>管理站内通知、邮件和欢迎/验证类消息，发送时选择通知方式。</p></div></div></div><div class="panel email-send-panel"><div class="section-title"><h3>发送通知</h3><span class="section-note">可选择站内通知、邮件或同时发送</span></div><form method="post" action="/admin/email-templates/send" class="form-grid"><div><label class="form-label">选择模板</label><select class="form-control" name="templateId" required>${rows.map(row => `<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('')}</select></div><div><label class="form-label">发送方式</label><select class="form-control" name="channel" required><option value="site">仅站内通知</option><option value="email">仅邮件</option><option value="both">站内通知 + 邮件</option></select></div><div><label class="form-label">站内通知收件人</label><select class="form-control" name="recipientId"><option value="">不发送站内通知</option>${recipients.map(row => `<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.email)}</option>`).join('')}</select></div><div><label class="form-label">邮件收件邮箱</label><input class="form-control" type="email" name="to" placeholder="customer@example.com"></div><div><label class="form-label">客户姓名</label><input class="form-control" name="customer_name"></div><div><label class="form-label">订单编号</label><input class="form-control" name="order_number"></div><div><label class="form-label">合同编号</label><input class="form-control" name="contract_number"></div><div><label class="form-label">退款金额</label><input class="form-control" name="refund_amount"></div><div style="grid-column:1/-1"><button class="button button-primary" type="submit">发送通知</button></div></form></div><div class="panel email-template-list">${rows.map(row => `<form method="post" action="/admin/email-templates/${esc(row.id)}" class="email-template-card"><div class="section-title"><h3>${esc(row.name)}</h3><span class="badge ${row.enabled ? 'badge-success' : 'badge-neutral'}">${row.enabled ? '启用' : '停用'}</span></div><label class="form-label">主题</label><input class="form-control" name="subject" value="${esc(row.subject)}" required><label class="form-label">正文</label><textarea class="form-control" name="body" rows="5" required>${esc(row.body)}</textarea><small class="form-text">变量：{customer_name}、{order_number}、{contract_number}、{refund_amount}、{sign_url}</small><button class="button button-primary" type="submit">保存模板</button></form>`).join('')}</div>`
  return buildLayout('邮件通知模板 - 电脑租赁管理系统', body, user)
}
