import { buildLayout } from '../../site'

export async function renderAdminEmailTemplates(c: any, user: any) {
  await c.env.RENT.prepare('CREATE TABLE IF NOT EXISTS email_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run()
  try { await c.env.RENT.prepare("ALTER TABLE email_templates ADD COLUMN format TEXT NOT NULL DEFAULT 'markdown'").run() } catch (_) {}
  try { await c.env.RENT.prepare("ALTER TABLE email_templates ADD COLUMN theme_color TEXT NOT NULL DEFAULT '#f0a35b'").run() } catch (_) {}
  // 内置模板的兜底植入（仅当迁移未跑、对应行缺失时生效）。正文为结构化 HTML，
  // 与 migrations/0120_richen_email_templates.sql 的范式一致；已存在的行不会被覆盖。
  const footer = '<hr style="border:0; border-top:1px solid #ddd; margin:24px 0;"><p style="font-size:12px; color:#888;">此邮件由系统自动发送，请勿直接回复。</p>'
  const sign = '<p><strong>{company_name}</strong><br>{company_email}</p>'
  const seed = (id: string, name: string, subject: string, body: string) =>
    c.env.RENT.prepare("INSERT OR IGNORE INTO email_templates (id, name, subject, body, format) VALUES (?, ?, ?, ?, 'html')").bind(id, name, subject, body)
  await c.env.RENT.batch([
    seed('email_verification', '验证邮箱', '请验证您的邮箱 - {company_name}',
      `<h2>验证您的邮箱</h2><p>您好 {customer_name}：</p><p>感谢您注册 <strong>{company_name}</strong>。请验证您的邮箱地址以完成账户激活。</p><h3>验证详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">邮箱地址</td><td style="padding:8px 0;"><strong>{customer_email}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">链接有效期</td><td style="padding:8px 0;">24 小时</td></tr></tbody></table><p>请点击以下链接验证您的邮箱地址：<br><a href="{verification_url}">{verification_url}</a></p><p>如需帮助，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`),
    seed('welcome_site', '欢迎邮件', '欢迎加入 {company_name}',
      `<h2>欢迎加入 {company_name}</h2><p>您好 {customer_name}：</p><p>欢迎使用 <strong>{company_name}</strong> 设备租赁服务。您的账户已创建成功。</p><h3>账户信息</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">账户姓名</td><td style="padding:8px 0;"><strong>{customer_name}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">登录邮箱</td><td style="padding:8px 0;">{customer_email}</td></tr></tbody></table><p>您现在可以浏览设备、在线下单并电子签署租赁合同。如需帮助，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`),
    seed('order_created', '订单已创建', '订单已创建 - {order_number}',
      `<h2>订单已创建</h2><p>您好 {customer_name}：</p><p>您的订单已成功创建。感谢您选择 <strong>{company_name}</strong>。</p><h3>订单详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">合同编号</td><td style="padding:8px 0;">{contract_number}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁期间</td><td style="padding:8px 0;">{start_date} 至 {end_date}</td></tr><tr><td style="padding:8px 0; color:#666;">租赁时长</td><td style="padding:8px 0;">{rental_period}</td></tr><tr><td style="padding:8px 0; color:#666;">订单金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">押金</td><td style="padding:8px 0;">{deposit_amount}</td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在 <strong>{payment_due_date}</strong> 前完成付款并电子签署租赁合同。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('order_approved', '订单审核通过', '订单审核通过 - {order_number}',
      `<h2>订单审核通过</h2><p>您好 {customer_name}：</p><p>您的订单已通过审核。感谢您选择 <strong>{company_name}</strong>。</p><h3>订单详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">应付金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在 <strong>{payment_due_date}</strong> 前完成付款，逾期订单可能被自动取消。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('payment_reminder', '付款提醒', '付款提醒 - {order_number}',
      `<h2>付款提醒</h2><p>您好 {customer_name}：</p><p>我们注意到您的订单尚未完成付款。感谢您选择 <strong>{company_name}</strong>。</p><h3>待付款详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">待付金额</td><td style="padding:8px 0;"><strong>{total_amount}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">付款截止</td><td style="padding:8px 0;">{payment_due_date}</td></tr></tbody></table><p>请在付款截止日 <strong>{payment_due_date}</strong> 前完成付款，以免订单被取消。如已完成付款或有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('pickup_reminder', '取件提醒', '取件提醒 - {order_number}',
      `<h2>取件提醒</h2><p>您好 {customer_name}：</p><p>您的设备已准备就绪，请按下方安排取件。感谢您选择 <strong>{company_name}</strong>。</p><h3>取件详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">取件日期</td><td style="padding:8px 0;"><strong>{pickup_date}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">取件地点</td><td style="padding:8px 0;">{pickup_location}</td></tr></tbody></table><p>取件时请当场检查设备外观与功能并确认无误。如需调整取件时间，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('return_confirmed', '归还确认', '设备归还确认 - {order_number}',
      `<h2>设备归还确认</h2><p>您好 {customer_name}：</p><p>我们已确认收到您归还的设备。感谢您选择 <strong>{company_name}</strong>。</p><h3>归还详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">订单编号</td><td style="padding:8px 0;"><strong>{order_number}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">租赁设备</td><td style="padding:8px 0;">{device_name}</td></tr><tr><td style="padding:8px 0; color:#666;">归还日期</td><td style="padding:8px 0;">{return_date}</td></tr></tbody></table><p>我们将对设备进行验机。押金结算与退款结果将另行通知，通常在 10 个营业日内完成。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>，并提供订单编号 <strong>{order_number}</strong>。</p>${sign}${footer}`),
    seed('password_reset', '密码重置', '重置您的登录密码 - {company_name}',
      `<h2>重置登录密码</h2><p>您好 {customer_name}：</p><p>我们收到了重置您账户密码的请求。若非本人操作，请忽略本邮件，您的密码不会被更改。</p><h3>重置详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">账户邮箱</td><td style="padding:8px 0;"><strong>{customer_email}</strong></td></tr><tr><td style="padding:8px 0; color:#666;">链接有效期</td><td style="padding:8px 0;">24 小时</td></tr></tbody></table><p>请通过以下链接重置密码，链接过期后请重新申请：<br><a href="{reset_url}">{reset_url}</a></p><p>如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}<hr style="border:0; border-top:1px solid #ddd; margin:24px 0;"><p style="font-size:12px; color:#888;">此邮件由系统自动发送，请勿直接回复。如果您并未申请重置密码，请立即联系 {company_name}。</p>`),
    seed('agreement_update', '协议更新通知', '协议内容已更新 - {company_name}',
      `<h2>协议内容已更新</h2><p>您好 {customer_name}：</p><p>我们更新了以下协议内容，特此通知。感谢您选择 <strong>{company_name}</strong>。</p><h3>更新详情</h3><table style="width:100%; border-collapse:collapse;"><tbody><tr><td style="padding:8px 0; color:#666;">更新内容</td><td style="padding:8px 0;"><strong>{changed_agreements}</strong></td></tr></tbody></table><p>最新版本已在我们网站的对应页面公布。继续使用服务即视为接受更新后的内容；如不同意，您可以联系我们并停止使用相关服务。如有疑问，请联系 <a href="mailto:{company_email}">{company_email}</a>。</p>${sign}${footer}`)
  ])
  const rows = (await c.env.RENT.prepare('SELECT * FROM email_templates ORDER BY name').all()).results as any[]
  const pageSize = 10
  const pageCount = Math.max(1, Math.ceil(rows.length / pageSize))
  const page = Math.min(Math.max(1, Number(new URL(c.req.url).searchParams.get('page') || 1) || 1), pageCount)
  const pageRows = rows.slice((page - 1) * pageSize, page * pageSize)
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const variables = '{customer_name}、{customer_email}、{order_number}、{contract_number}、{device_name}、{start_date}、{end_date}、{rental_period}、{pickup_date}、{pickup_location}、{return_date}、{return_location}、{total_amount}、{deposit_amount}、{refund_amount}、{payment_due_date}、{sign_url}、{verification_url}、{reset_url}、{company_name}、{company_email}'
  const variableIndex = `<details class="variable-index"><summary>可用变量（${variables.split('、').length} 项）</summary><section class="contract-variable-group"><div class="variable-chip-list">${variables.split('、').map(variable => `<code>${variable}</code>`).join('')}</div></section></details>`
  const isBuiltin = (id: string) => !String(id).startsWith('custom_')
  const themeOf = (row: any) => row.theme_color || (isBuiltin(row.id) ? '#f0a35b' : '#71818d')

  const createForm = `<div class="panel"><div class="section-title"><h3>新建模板</h3><span class="section-note">管理员可创建自定义通知模板</span></div><form method="post" action="/admin/email-templates" class="form-grid"><div><label class="form-label">模板名称</label><input class="form-control" name="name" maxlength="80" required></div><div><label class="form-label">邮件主题</label><input class="form-control" name="subject" maxlength="200" required></div><div><label class="form-label">主题色</label><input class="form-control" type="color" name="theme_color" value="#71818d"></div><div style="grid-column:1/-1"><label class="form-label">正文（HTML）</label><textarea class="form-control html-editor" name="body" rows="8" maxlength="10000" required></textarea></div><div style="grid-column:1/-1">${variableIndex}</div><div style="grid-column:1/-1"><button class="button button-primary" type="submit">添加模板</button></div></form></div>`

  const items = pageRows.map(row => {
    const builtin = isBuiltin(row.id)
    return `<details class="record-archive__item" data-search="${esc(`${row.name} ${row.subject} ${row.body}`).toLowerCase()}"><summary class="record-archive__summary"><span class="record-archive__seq">${builtin ? '内置' : '自定义'}</span><span class="record-archive__title">${esc(row.name)}</span><span class="record-archive__meta"><span class="badge ${row.enabled ? 'badge-success' : 'badge-neutral'}">${row.enabled ? '启用' : '停用'}</span></span></summary><div class="record-archive__body"><form method="post" action="/admin/email-templates/${esc(row.id)}"><label class="form-label">主题</label><input class="form-control" name="subject" value="${esc(row.subject)}" maxlength="200" required><label class="form-label">主题色</label><input class="form-control" type="color" name="theme_color" value="${esc(themeOf(row))}"><label class="form-label">正文（HTML）</label><textarea class="form-control html-editor" name="body" rows="8" maxlength="10000" required>${esc(row.body)}</textarea><div class="record-archive__actions"><button class="button button-primary" type="submit">保存模板</button></div></form>${builtin ? '' : `<form method="post" action="/admin/email-templates/${esc(row.id)}/delete" onsubmit="return confirm('确定删除这个自定义模板吗？')"><button class="button button-sm button-danger" type="submit">删除模板</button></form>`}</div></details>`
  }).join('')

  const countLabel = pageCount > 1 ? `第 ${page}/${pageCount} 页 · 共 ${rows.length} 条` : `共 ${rows.length} 条`
  const pagination = pageCount > 1 ? `<nav class="record-archive__pagination" aria-label="通知模板分页">${Array.from({ length: pageCount }, (_, i) => `<a class="button button-sm ${i + 1 === page ? 'button-primary' : 'button-secondary'}" href="/admin/email-templates?page=${i + 1}">${i + 1}</a>`).join('')}</nav>` : ''
  const archive = `<div class="record-archive"><div class="record-archive__toolbar"><input type="search" id="templateSearch" class="form-control" placeholder="在本页搜索名称、主题或正文…" autocomplete="off"><span class="record-archive__count" id="templateCount" data-base="${countLabel}">${countLabel}</span></div><div class="record-archive__list">${items}</div><p class="empty-state" id="templateNoResult" style="display:none">本页没有匹配的模板</p>${pagination}</div>`

  const script = `<script>(()=>{const s=document.getElementById('templateSearch');if(!s)return;const list=[...document.querySelectorAll('.record-archive__item')];const count=document.getElementById('templateCount');const none=document.getElementById('templateNoResult');const run=()=>{const q=s.value.trim().toLowerCase();let n=0;list.forEach(it=>{const hit=!q||(it.dataset.search||'').includes(q);it.style.display=hit?'':'none';if(hit)n++;});count.textContent=q?('匹配 '+n+' 条'):count.dataset.base;none.style.display=q&&!n?'':'none';};s.addEventListener('input',run);})();</script>`

  const body = `<div class="entity-header"><div class="identity-strip mono"><span>COMMUNICATION / NOTIFICATIONS</span><span>${rows.length} TEMPLATES</span></div><div class="entity-heading"><div><p class="section-code">MESSAGE LIBRARY</p><h2>通知模板</h2><p>管理站内通知、邮件和欢迎/验证类消息，点击模板名称展开编辑。</p></div></div></div>${createForm}${archive}${script}`
  return buildLayout('邮件通知模板 - 电脑租赁管理系统', body, user)
}
