/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0.
 * Noncommercial use, modification, and distribution are permitted.
 * Keep this notice and the LICENSE file with all copies and modified versions. */

import { buildLayout } from '../../site'
import { ensureInAppNotificationTemplates } from '../../services/inAppNotificationTemplates'

export async function renderAdminInAppNotificationTemplates(c: any, user: any) {
  await ensureInAppNotificationTemplates(c)
  const rows = (await c.env.RENT.prepare('SELECT * FROM in_app_notification_templates ORDER BY name').all()).results as any[]
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const variables = '{title}、{message}、{customer_name}、{customer_email}、{order_number}、{invoice_number}、{receipt_number}、{contract_number}、{device_name}、{start_date}、{end_date}、{rental_period}、{pickup_date}、{pickup_time}、{pickup_location}、{return_date}、{return_time}、{return_location}、{total_amount}、{deposit_amount}、{refund_amount}、{payment_due_date}、{delivery_method}、{delivery_address}、{delivery_fee}、{rental_note}、{order_detail_url}、{sign_url}、{verification_url}、{reset_url}、{company_name}、{company_email}'
  const variableIndex = `<details class="variable-index"><summary>可用变量（${variables.split('、').length} 项）</summary><section class="contract-variable-group"><div class="variable-chip-list">${variables.split('、').map(variable => `<code>${variable}</code>`).join('')}</div></section></details>`
  const isBuiltin = (id: string) => !String(id).startsWith('custom_')

  const createForm = `<div class="panel"><div class="section-title"><h3>新建模板</h3><span class="section-note">用于发送站内通知，不会附加邮件外壳</span></div><form method="post" action="/admin/in-app-notification-templates" class="form-grid"><div><label class="form-label">模板名称</label><input class="form-control" name="name" maxlength="80" required></div><div style="grid-column:1/-1"><label class="form-label">通知标题</label><input class="form-control" name="title" maxlength="120" required></div><div style="grid-column:1/-1"><label class="form-label">通知正文（支持 HTML）</label><textarea class="form-control html-editor" name="message" rows="8" maxlength="10000" required></textarea></div><div style="grid-column:1/-1">${variableIndex}</div><div style="grid-column:1/-1"><button class="button button-primary" type="submit">添加模板</button></div></form></div>`
  const items = rows.map(row => {
    const builtin = isBuiltin(row.id)
    return `<details class="record-archive__item" data-search="${esc(`${row.name} ${row.title} ${row.message}`).toLowerCase()}"><summary class="record-archive__summary"><span class="record-archive__seq">${builtin ? '内置' : '自定义'}</span><span class="record-archive__title">${esc(row.name)}</span><span class="record-archive__meta"><span class="badge ${row.enabled ? 'badge-success' : 'badge-neutral'}">${row.enabled ? '启用' : '停用'}</span></span></summary><div class="record-archive__body"><form method="post" action="/admin/in-app-notification-templates/${encodeURIComponent(row.id)}"><label class="form-label">通知标题</label><input class="form-control" name="title" value="${esc(row.title)}" maxlength="120" required><label class="form-label">通知正文（支持 HTML）</label><textarea class="form-control html-editor" name="message" rows="8" maxlength="10000" required>${esc(row.message)}</textarea><div class="record-archive__actions"><button class="button button-primary" type="submit">保存模板</button></div></form>${builtin ? '' : `<form method="post" action="/admin/in-app-notification-templates/${encodeURIComponent(row.id)}/delete" onsubmit="return confirm('确定删除这个自定义模板吗？')"><button class="button button-sm button-danger" type="submit">删除模板</button></form>`}</div></details>`
  }).join('')
  const body = `<div class="entity-header"><div class="identity-strip mono"><span>COMMUNICATION / IN-APP</span><span>${rows.length} TEMPLATES</span></div><div class="entity-heading"><div><p class="section-code">MESSAGE LIBRARY</p><h2>站内通知模板</h2><p>管理通知中心使用的标题和正文。初始内容来自邮件模板，但后续编辑互不影响。</p></div></div></div>${createForm}<div class="record-archive"><div class="record-archive__toolbar"><input type="search" id="templateSearch" class="form-control" placeholder="搜索名称、标题或正文…" autocomplete="off"><span class="record-archive__count" id="templateCount" data-base="共 ${rows.length} 条">共 ${rows.length} 条</span></div><div class="record-archive__list">${items}</div><p class="empty-state" id="templateNoResult" style="display:none">没有匹配的模板</p></div><script>(()=>{const s=document.getElementById('templateSearch');if(!s)return;const list=[...document.querySelectorAll('.record-archive__item')];const count=document.getElementById('templateCount');const none=document.getElementById('templateNoResult');const run=()=>{const q=s.value.trim().toLowerCase();let n=0;list.forEach(it=>{const hit=!q||(it.dataset.search||'').includes(q);it.style.display=hit?'':'none';if(hit)n++;});count.textContent=q?('匹配 '+n+' 条'):count.dataset.base;none.style.display=q&&!n?'':'none';};s.addEventListener('input',run);})();</script>`
  return buildLayout('站内通知模板 - 电脑租赁管理系统', body, user)
}
