/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0.
 * Noncommercial use, modification, and distribution are permitted.
 * Keep this notice and the LICENSE file with all copies and modified versions. */

import { buildLayout } from '../../site'
import { ensureInAppNotificationTemplates } from '../../services/inAppNotificationTemplates'

export async function renderAdminInAppNotificationTemplates(c: any, user: any) {
  await ensureInAppNotificationTemplates(c)
  const rows = (await c.env.RENT.prepare('SELECT * FROM in_app_notification_templates ORDER BY name').all()).results as any[]
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const variables = '{title}、{message}、{customer_name}、{customer_email}、{order_number}、{invoice_number}、{receipt_number}、{contract_number}、{device_name}、{start_date}、{end_date}、{rental_period}、{pickup_date}、{pickup_time}、{pickup_location}、{return_date}、{return_time}、{return_location}、{total_amount}、{deposit_amount}、{refund_amount}、{payment_due_date}、{delivery_method}、{delivery_address}、{delivery_fee}、{rental_note}、{order_detail_url}、{sign_url}、{verification_url}、{reset_url}、{company_name}、{company_email}'
  const variableIndex = `<details class="variable-index"><summary>可用变量（${variables.split('、').length} 项）</summary><section class="contract-variable-group"><div class="variable-chip-list">${variables.split('、').map(variable => `<code>${variable}</code>`).join('')}</div></section></details>`
  const isBuiltin = (id: string) => !String(id).startsWith('custom_')
  const builtinCount = rows.filter(row => isBuiltin(row.id)).length
  const customCount = rows.length - builtinCount
  const preview = (value: unknown) => String(value ?? '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 92)

  const createForm = `<section class="in-app-template-composer"><div class="in-app-template-composer__head"><div><p class="section-code">NEW MESSAGE</p><h3>新建站内模板</h3><p>保存后可在“发布通知”里直接选择。</p></div><span class="in-app-template-composer__hint">通知内容直接呈现给收件人</span></div><form method="post" action="/admin/in-app-notification-templates" class="form-grid in-app-template-form"><div><label class="form-label">模板名称</label><input class="form-control" name="name" maxlength="80" required placeholder="例如：订单状态更新"></div><div style="grid-column:1/-1"><label class="form-label">通知标题</label><input class="form-control" name="title" maxlength="120" required placeholder="例如：您的订单已创建"></div><div style="grid-column:1/-1"><label class="form-label">通知正文 <span class="form-label__note">支持安全 HTML</span></label><textarea class="form-control html-editor" name="message" rows="8" maxlength="10000" required placeholder="向收件人说明下一步需要做什么…"></textarea></div><div style="grid-column:1/-1">${variableIndex}</div><div class="in-app-template-form__footer" style="grid-column:1/-1"><span>不会发送邮件，也不会附加邮件页眉或页脚。</span><button class="button button-primary" type="submit">保存站内模板</button></div></form></section>`
  const items = rows.map(row => {
    const builtin = isBuiltin(row.id)
    return `<details class="record-archive__item in-app-template-card" data-search="${esc(`${row.name} ${row.title} ${row.message}`).toLowerCase()}"><summary class="record-archive__summary"><span class="record-archive__seq">${builtin ? '内置' : '自定义'}</span><span class="in-app-template-card__copy"><span class="record-archive__title">${esc(row.name)}</span><small>${esc(row.title)} · ${esc(preview(row.message)) || '尚未填写正文'}</small></span><span class="record-archive__meta"><span class="badge ${row.enabled ? 'badge-success' : 'badge-neutral'}">${row.enabled ? '可用' : '停用'}</span></span></summary><div class="record-archive__body"><form method="post" action="/admin/in-app-notification-templates/${encodeURIComponent(row.id)}"><label class="form-label">通知标题</label><input class="form-control" name="title" value="${esc(row.title)}" maxlength="120" required><label class="form-label">通知正文 <span class="form-label__note">支持安全 HTML</span></label><textarea class="form-control html-editor" name="message" rows="8" maxlength="10000" required>${esc(row.message)}</textarea><div class="record-archive__actions"><button class="button button-primary" type="submit">保存更改</button></div></form>${builtin ? '' : `<form method="post" action="/admin/in-app-notification-templates/${encodeURIComponent(row.id)}/delete" onsubmit="return confirm('确定删除这个自定义模板吗？')"><button class="button button-sm button-danger" type="submit">删除模板</button></form>`}</div></details>`
  }).join('')
  const body = `<section class="in-app-template-hero"><div class="in-app-template-hero__copy"><p class="section-code">COMMUNICATION / IN-APP</p><h2>站内通知模板</h2><p>把关键消息写得清楚、及时、可行动。内容直接出现在收件人的通知中心，不经过邮件排版。</p><div class="in-app-template-hero__stats"><span><b>${rows.length}</b> 个模板</span><span><b>${builtinCount}</b> 个内置</span><span><b>${customCount}</b> 个自定义</span></div></div><aside class="in-app-template-preview" aria-label="站内通知预览"><div class="in-app-template-preview__bar"><span class="in-app-template-preview__dot"></span><span>通知中心</span><time>刚刚</time></div><div class="in-app-template-preview__content"><strong>订单已创建</strong><p>您的订单已创建，请在付款截止前完成付款并签署合同。</p><small>这是站内显示效果，不含邮件外壳。</small></div></aside></section>${createForm}<section class="in-app-template-library"><div class="in-app-template-library__head"><div><p class="section-code">TEMPLATE LIBRARY</p><h3>已保存的模板</h3></div><a class="button button-secondary" href="/notifications#send-notification">去发布通知</a></div><div class="record-archive"><div class="record-archive__toolbar"><input type="search" id="templateSearch" class="form-control" placeholder="搜索名称、标题或正文…" autocomplete="off"><span class="record-archive__count" id="templateCount" data-base="共 ${rows.length} 条">共 ${rows.length} 条</span></div><div class="record-archive__list">${items}</div><p class="empty-state" id="templateNoResult" style="display:none">没有匹配的模板</p></div></section><script>(()=>{const s=document.getElementById('templateSearch');if(!s)return;const list=[...document.querySelectorAll('.record-archive__item')];const count=document.getElementById('templateCount');const none=document.getElementById('templateNoResult');const run=()=>{const q=s.value.trim().toLowerCase();let n=0;list.forEach(it=>{const hit=!q||(it.dataset.search||'').includes(q);it.style.display=hit?'':'none';if(hit)n++;});count.textContent=q?('匹配 '+n+' 条'):count.dataset.base;none.style.display=q&&!n?'':'none';};s.addEventListener('input',run);})();</script>`
  return buildLayout('站内通知模板 - 电脑租赁管理系统', body, user)
}
