import type { Context } from 'hono'
import { buildLayout, formatCurrency, sanitizePlainText } from '../../site'

const esc = (value: unknown) => sanitizePlainText(value, 500).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

export async function renderAdminPaymentReviews(c: Context, user: any) {
  const topups = (await c.env.RENT.prepare("SELECT t.*, u.name AS user_name, u.email AS user_email FROM balance_topups t LEFT JOIN users u ON u.id = t.user_id WHERE t.status = 'submitted' ORDER BY t.updated_at DESC, t.created_at DESC").all()).results || []
  const proofs = (await c.env.RENT.prepare("SELECT pp.id, pp.reference_number, pp.note, pp.image_url AS proof_image_url, pp.uploaded_at, p.rental_id, p.amount, o.orderNo, u.name AS user_name, u.email AS user_email FROM payment_proofs pp JOIN payments p ON p.id = pp.payment_id JOIN orders o ON o.id = p.rental_id LEFT JOIN users u ON u.id = p.customer_id WHERE pp.status = 'submitted' AND o.status <> 'active' ORDER BY pp.uploaded_at DESC").all()).results || []
  const methodLabel = (method: string) => ({ bank_transfer: '银行转账', alipay: '支付宝', wechat: '微信' } as Record<string, string>)[method] || method
  const topupRows = topups.map((item: any) => `<tr data-review-row data-search="${esc([item.user_name, item.user_email, item.reference, item.note].join(' '))}"><td><strong>${esc(item.user_name || item.user_email || item.user_id)}</strong><small>${esc(item.user_email)}</small></td><td><strong class="mono">${formatCurrency(item.amount)}</strong><small>${esc(methodLabel(item.payment_method))}</small></td><td class="mono">${esc(item.reference || '-')}</td><td>${item.proof_image_url ? `<a class="proof-link" href="${esc(item.proof_image_url)}" target="_blank" rel="noopener"><img src="${esc(item.proof_image_url)}" alt="付款凭证" loading="lazy">查看凭证</a>` : '<span class="section-note">未上传</span>'}${item.note ? `<small>${esc(item.note)}</small>` : ''}</td><td class="mono">${esc(item.updated_at || item.created_at)}</td><td class="review-actions"><form method="post" action="/admin/balance-topups/${encodeURIComponent(item.id)}/approve" data-site-confirm="确认通过这笔充值并立即入账吗？"><button class="button button-sm button-primary" type="submit">通过并入账</button></form><form method="post" action="/admin/balance-topups/${encodeURIComponent(item.id)}/reject" data-site-confirm="确认驳回这笔充值吗？"><button class="button button-sm button-danger" type="submit">驳回</button></form></td></tr>`).join('')
  const proofRows = proofs.map((item: any) => `<tr data-review-row data-search="${esc([item.user_name, item.user_email, item.orderNo, item.reference_number, item.note].join(' '))}"><td><strong>${esc(item.user_name || item.user_email)}</strong><small>${esc(item.user_email)}</small></td><td><a class="mono" href="/admin/orders/${encodeURIComponent(item.rental_id)}">${esc(item.orderNo || item.rental_id)}</a><small>${esc(item.note || '订单付款')}</small></td><td class="mono"><strong>${formatCurrency(item.amount)}</strong></td><td class="mono">${esc(item.reference_number || '-')}</td><td>${item.proof_image_url ? `<a class="proof-link" href="${esc(item.proof_image_url)}" target="_blank" rel="noopener"><img src="${esc(item.proof_image_url)}" alt="转账凭证" loading="lazy">查看凭证</a>` : '<span class="section-note">未上传</span>'}</td><td class="mono">${esc(item.uploaded_at)}</td><td class="review-actions"><form method="post" action="/admin/orders/${encodeURIComponent(item.rental_id)}/transfer-proof/approve" data-site-confirm="确认通过付款并将订单标记为已付款吗？"><button class="button button-sm button-primary" type="submit">通过付款</button></form><form method="post" action="/admin/orders/${encodeURIComponent(item.rental_id)}/transfer-proof/reject" data-site-confirm="确认驳回这笔付款凭证吗？"><input type="hidden" name="reason" value="凭证未通过审核"><button class="button button-sm button-danger" type="submit">驳回</button></form></td></tr>`).join('')
  const body = `<div class="page-header"><div><p class="section-code">PAYMENT REVIEW DESK / ${topups.length + proofs.length ? 'ACTION REQUIRED' : 'CLEAR'}</p><h2>充值与转账审核</h2><p>集中处理客户余额充值和订单付款凭证。审核通过后会立即产生对应的入账或订单状态变更。</p></div><div class="record-actions"><a class="button button-primary" href="#review-queue">查看待办</a><a class="button button-secondary" href="/admin/finance">财务总览</a></div></div><div class="stats-grid"><div class="stat-card warning"><h3>待审核充值</h3><div class="value">${topups.length}</div><div class="trend">余额充值 · 通过后入账</div></div><div class="stat-card accent"><h3>待审核付款</h3><div class="value">${proofs.length}</div><div class="trend">订单凭证 · 通过后变更订单</div></div><div class="stat-card"><h3>待处理总数</h3><div class="value">${topups.length + proofs.length}</div><div class="trend">${topups.length + proofs.length ? '建议按提交时间处理' : '当前队列已清空'}</div></div></div><div class="review-toolbar" id="review-queue"><div><span class="section-code">QUEUE FILTER</span><strong>待审核队列</strong></div><label class="review-search"><span>搜索客户、订单或 Reference</span><input id="reviewSearch" class="form-control" type="search" placeholder="输入关键词筛选…"></label><span class="section-note" id="reviewCount">共 ${topups.length + proofs.length} 笔</span></div><section class="panel review-panel"><div class="section-title"><div><span class="section-code">WALLET FUNDING</span><h3>余额充值</h3></div><span class="section-note">待审核 ${topups.length} 笔</span></div>${topups.length ? `<div class="table-wrapper review-table"><table><thead><tr><th>客户</th><th>金额 / 方式</th><th>Reference</th><th>凭证 / 备注</th><th>提交时间</th><th>操作</th></tr></thead><tbody>${topupRows}</tbody></table></div>` : '<p class="empty-state">暂无待审核充值，客户提交付款凭证后会出现在这里。</p>'}</section><section class="panel review-panel"><div class="section-title"><div><span class="section-code">ORDER PAYMENTS</span><h3>订单转账付款</h3></div><span class="section-note">待审核 ${proofs.length} 笔</span></div>${proofs.length ? `<div class="table-wrapper review-table"><table><thead><tr><th>客户</th><th>订单 / 备注</th><th>金额</th><th>Reference</th><th>凭证</th><th>提交时间</th><th>操作</th></tr></thead><tbody>${proofRows}</tbody></table></div>` : '<p class="empty-state">暂无待审核转账付款，当前订单付款队列已清空。</p>'}</section><script>(()=>{const input=document.getElementById('reviewSearch'),rows=[...document.querySelectorAll('[data-review-row]')],count=document.getElementById('reviewCount');input?.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();let visible=0;rows.forEach(row=>{const show=!q||String(row.dataset.search||'').toLowerCase().includes(q);row.hidden=!show;if(show)visible++;});if(count)count.textContent='显示 '+visible+' / '+rows.length+' 笔';});})();</script>`
  return buildLayout('充值与转账审核 - 电脑租赁管理系统', body, user)
}
