import { buildLayout, formatCurrency, sanitizePlainText } from '../../site'

const esc = (value: unknown, limit = 500) => sanitizePlainText(value, limit).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
const labels: Record<string, string> = { DISPUTE_OPENED: '已发起', DISPUTE_UNDER_REVIEW: '证据准备中', DISPUTE_WON: '争议胜诉', DISPUTE_LOST: '争议败诉', DISPUTE_CLOSED: '已关闭' }

export function renderAdminPaymentDisputes(user: any, disputes: any[] = []) {
  const isOpen = (item: any) => ['DISPUTE_OPENED', 'DISPUTE_UNDER_REVIEW'].includes(String(item.status))
  const open = disputes.filter(isOpen)
  const rows = disputes.map(item => `<tr><td><strong>${esc(item.order_no || item.order_id || '-')}</strong><small>${esc(item.customer_name || item.customer_email || item.customer_id || '-')}</small></td><td class="mono">${formatCurrency(Number(item.amount || 0))}<small>${esc(item.currency || 'AUD', 10)} · ${esc(item.reason || '未提供原因', 200)}</small></td><td><span class="badge ${isOpen(item) ? 'badge-warning' : item.status === 'DISPUTE_WON' ? 'badge-success' : item.status === 'DISPUTE_LOST' ? 'badge-danger' : 'badge-neutral'}">${esc(labels[item.status] || item.status, 80)}</span><small>最晚举证：${esc(item.evidence_due_by || '未提供', 80)}</small></td><td>${isOpen(item) ? `<form method="post" action="/admin/finance/payment-disputes/${encodeURIComponent(item.id)}" style="display:grid;gap:7px;min-width:220px"><select class="form-control" name="status"><option value="DISPUTE_UNDER_REVIEW" ${item.status === 'DISPUTE_UNDER_REVIEW' ? 'selected' : ''}>证据准备中</option><option value="DISPUTE_WON">争议胜诉</option><option value="DISPUTE_LOST">争议败诉</option><option value="DISPUTE_CLOSED">关闭争议</option></select><input class="form-control" name="evidenceStatus" maxlength="200" value="${esc(item.evidence_status || '', 200)}" placeholder="证据状态 / 提交说明"><input class="form-control" name="financialImpact" type="number" min="0" step="0.01" value="${item.financial_impact == null ? '' : esc(item.financial_impact, 30)}" placeholder="实际财务影响"><textarea class="form-control" name="result" maxlength="1000" placeholder="处理结论（结案时必填）">${esc(item.result || '', 1000)}</textarea><button class="button button-sm button-primary" type="submit">保存处理结果</button></form>` : `<p>${esc(item.result || '暂无处理结论', 1000)}</p><small>证据：${esc(item.evidence_status || '未记录', 200)} · 财务影响：${item.financial_impact == null ? '-' : formatCurrency(Number(item.financial_impact))}</small>`}</td></tr>`).join('')
  const body = `<div class="page-header"><div><p class="section-code">FINANCE / PAYMENT DISPUTES</p><h2>支付争议管理</h2><p>处理 Stripe 拒付争议、记录举证进度与最终财务影响。</p></div><a class="button button-secondary" href="/admin/finance">返回财务总览</a></div><div class="stats-grid"><div class="stat-card warning"><h3>待处理争议</h3><div class="value">${open.length}</div></div><div class="stat-card"><h3>待处理金额</h3><div class="value">${formatCurrency(open.reduce((sum, item) => sum + Number(item.amount || 0), 0))}</div></div><div class="stat-card"><h3>历史争议</h3><div class="value">${disputes.length}</div></div></div><section class="panel"><div class="section-title"><h3>争议队列</h3><span class="section-note">由 Stripe Webhook 自动创建</span></div>${rows ? `<div class="table-wrapper"><table><thead><tr><th>订单 / 客户</th><th>争议金额与原因</th><th>状态</th><th>处理</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty-state"><h3>暂无支付争议</h3><p>收到 Stripe 拒付事件后会自动出现在这里。</p></div>'}</section>`
  return buildLayout('支付争议管理 - 电脑租赁管理系统', body, user)
}
