/* Copyright (c) 2026 jiongjiong123441. All rights reserved.
 * Licensed under PolyForm Noncommercial 1.0.0.
 * Noncommercial use, modification, and distribution are permitted.
 * Keep this notice and the LICENSE file with all copies and modified versions. */

import { buildLayout, getSystemSettings } from '../../site'

export function renderAdminTaxInvoiceTemplate(user: any): string {
  const template = (getSystemSettings().taxInvoiceTemplate || {}) as Record<string, string>
  const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, x => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[x] || x))
  const current = (key: string, fallback: string) => String(template[key] || fallback)
  const input = (id: string, label: string, key: string, fallback: string) => `<label class="tax-invoice-field" for="${id}"><span>${label}</span><input class="form-control" id="${id}" data-template-key="${key}" value="${esc(current(key, fallback))}"></label>`
  const textarea = (id: string, label: string, key: string, fallback: string) => `<label class="tax-invoice-field tax-invoice-field--wide" for="${id}"><span>${label}</span><textarea class="form-control" id="${id}" data-template-key="${key}" rows="2">${esc(current(key, fallback))}</textarea></label>`
  const preview = (key: string, fallback: string) => `<span class="tax-invoice-preview__editable" contenteditable="true" role="textbox" spellcheck="false" data-preview="${key}" data-fallback="${esc(fallback)}">${esc(current(key, fallback))}</span>`
  const section = (number: string, title: string, description: string, fields: string) => `<section class="tax-invoice-editor__section"><div class="tax-invoice-editor__section-head"><span>${number}</span><div><h3>${title}</h3><p>${description}</p></div></div><div class="tax-invoice-editor__fields">${fields}</div></section>`

  const identity = [
    input('taxInvoiceTitle', 'Document title', 'title', 'TAX INVOICE'),
    input('taxInvoiceAbnLabel', 'ABN label', 'abnLabel', 'ABN'),
    input('taxInvoiceDocumentNumberLabel', 'Invoice number label', 'documentNumberLabel', 'INVOICE NO.'),
    input('taxInvoiceIssuedLabel', 'Issued label', 'issuedLabel', 'Issued'),
    textarea('taxInvoiceInvoiceMessage', 'Invoice message', 'invoiceMessage', 'Thank you for your business.'),
  ].join('')
  const columns = [
    input('taxInvoiceBilledToLabel', 'Billed-to heading', 'billedToLabel', 'BILLED TO'),
    input('taxInvoiceRentalOrderLabel', 'Rental order heading', 'rentalOrderLabel', 'RENTAL ORDER'),
    input('taxInvoicePaymentLabel', 'Payment heading', 'paymentLabel', 'Payment'),
    input('taxInvoiceDescriptionLabel', 'Description label', 'descriptionLabel', 'DESCRIPTION'),
    input('taxInvoiceItemLabel', 'Item column label', 'itemLabel', 'ITEM'),
    input('taxInvoiceQuantityLabel', 'Quantity column label', 'quantityLabel', 'QTY'),
    input('taxInvoicePriceLabel', 'Price column label', 'priceLabel', 'PRICE'),
    input('taxInvoiceAmountLabel', 'Amount column label', 'amountLabel', 'AMOUNT (AUD)'),
  ].join('')
  const totals = [
    input('taxInvoiceSubtotalLabel', 'Subtotal label', 'subtotalLabel', 'Subtotal'),
    input('taxInvoiceGstLabel', 'GST label', 'gstLabel', 'GST'),
    input('taxInvoiceDepositLabel', 'Deposit label', 'depositLabel', 'Refundable security deposit'),
    input('taxInvoiceProcessingFeeLabel', 'Processing fee label', 'processingFeeLabel', 'Payment processing fee'),
    input('taxInvoiceDiscountLabel', 'Discount label', 'discountLabel', 'Discount'),
    input('taxInvoiceTotalLabel', 'Total label', 'totalLabel', 'TOTAL PAID'),
  ].join('')
  const payment = [
    input('taxInvoiceContractLabel', 'Contract label', 'contractLabel', 'Contract'),
    input('taxInvoicePaidLabel', 'Paid label', 'paidLabel', 'Paid'),
    input('taxInvoicePaymentReferenceLabel', 'Payment reference label', 'paymentReferenceLabel', 'Payment reference'),
    input('taxInvoiceQuestionsLabel', 'Questions label', 'questionsLabel', 'Questions?'),
  ].join('')
  const footer = [
    textarea('taxInvoiceThankYouText', 'Thank-you text', 'thankYouText', 'Thank you for choosing our rental service.'),
    textarea('taxInvoiceRecordNote', 'Record note', 'recordNote', 'This document records the payment received for the rental order.'),
    textarea('taxInvoiceGeneratedByText', 'Generated-by text', 'generatedByText', 'Generated by the rental management system'),
  ].join('')
  const script = `<script>(()=>{const form=document.getElementById('taxInvoiceTemplateForm');if(!form)return;const fields=[...form.querySelectorAll('[data-template-key]')];const fieldFor=key=>fields.find(field=>field.dataset.templateKey===key);const values=()=>{const taxInvoiceTemplate={};fields.forEach(field=>{taxInvoiceTemplate[field.dataset.templateKey]=String(field.value||'').trim();});return taxInvoiceTemplate;};const refresh=()=>{const data=values();document.querySelectorAll('[data-preview]').forEach(node=>{const key=node.dataset.preview||'';if(document.activeElement!==node)node.textContent=data[key]||node.dataset.fallback||'';});};const save=async()=>{const response=await fetch('/admin/settings/save',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({taxInvoiceTemplate:values()})});const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{};}catch{data={error:raw||'保存失败'};}if(!response.ok||!data.success)throw new Error(data.error||'保存失败');const status=document.getElementById('taxInvoiceSaveStatus');if(status)status.textContent='已保存';setTimeout(()=>{if(status)status.textContent='实时预览';},2200);};fields.forEach(field=>field.addEventListener('input',refresh));document.querySelectorAll('[data-preview]').forEach(node=>{node.addEventListener('input',()=>{const field=fieldFor(node.dataset.preview||'');if(field)field.value=String(node.textContent||'').trim();});node.addEventListener('blur',refresh);});form.addEventListener('submit',event=>{event.preventDefault();const button=form.querySelector('button[type="submit"]');if(button)button.disabled=true;save().catch(error=>alert(error instanceof Error?error.message:'保存失败')).finally(()=>{if(button)button.disabled=false;});});refresh();})();</script>`
  const body = `<div class="page-header tax-invoice-editor__intro"><div><p class="section-code">FINANCE / DOCUMENTS / PDF</p><h2>Tax Invoice PDF 模板</h2><p>左侧编辑字段，右侧直接编辑 A4 英文 Tax Invoice 预览。预览中的英文文字可以点击修改。</p></div><a class="button button-secondary" href="/admin/settings">返回系统设置</a></div><div class="tax-invoice-editor"><form id="taxInvoiceTemplateForm" class="tax-invoice-editor__controls" novalidate><div class="tax-invoice-editor__controls-top"><div><span class="section-code">TEMPLATE EDITOR</span><strong>Australian GST invoice</strong></div><span class="tax-invoice-editor__status"><i></i><span id="taxInvoiceSaveStatus">实时预览</span></span></div>${section('01', 'Document identity', '控制发票顶部标题、编号和日期字段。', identity)}${section('02', 'Invoice columns', '对应明细表格与三栏信息的英文标签。', columns)}${section('03', 'Totals and GST', '控制金额汇总区域的英文标签。', totals)}${section('04', 'Payment details', '控制付款状态、合同和付款参考信息。', payment)}${section('05', 'Footer messages', '控制页面底部说明。', footer)}<div class="tax-invoice-editor__save"><button class="button button-primary" type="submit">保存 PDF 模板</button><span>保存后用于下载、邮件发送和管理员发送的 Tax Invoice。</span></div></form><div class="tax-invoice-editor__preview-shell"><div class="tax-invoice-editor__preview-bar"><div><span class="section-code">PREVIEW</span><strong>A4 / PDF</strong></div><span>示例数据</span></div><article class="tax-invoice-preview"><header class="tax-invoice-preview__header"><div class="tax-invoice-preview__brand"><div class="tax-invoice-preview__mark">PC</div><div><strong>PC RENTAL</strong><span>DEVICE RENTAL SERVICES</span><small>Street Address · Melbourne VIC</small></div></div><div class="tax-invoice-preview__meta"><strong>${preview('documentNumberLabel', 'INVOICE NO.')} 00000</strong><span>${preview('issuedLabel', 'Issued')} · 29/09/2026</span><span>${preview('abnLabel', 'ABN')} · 12 345 678 901</span></div></header><div class="tax-invoice-preview__rule"></div><div class="tax-invoice-preview__title"><h1>${preview('title', 'TAX INVOICE')}</h1><p>${preview('invoiceMessage', 'Thank you for your business.')}</p></div><div class="tax-invoice-preview__columns"><div><b>${preview('billedToLabel', 'BILLED TO')}</b><strong>Alex Morgan</strong><span>alex@example.com</span><span>Melbourne, VIC</span></div><div><b>${preview('rentalOrderLabel', 'RENTAL ORDER')}</b><strong>Rental order #R-1042</strong><span>${preview('contractLabel', 'Contract')} · CT-1042</span><span>Rental period · 01–07 Oct 2026</span></div><div><b>${preview('paymentLabel', 'Payment')}</b><strong>${preview('paidLabel', 'Paid')}</strong><span>${preview('paymentReferenceLabel', 'Payment reference')} · ch_123456</span><span>Visa ···· 4242</span></div></div><div class="tax-invoice-preview__table"><div class="tax-invoice-preview__table-head"><span>${preview('itemLabel', 'ITEM')}</span><span>${preview('quantityLabel', 'QTY')}</span><span>${preview('priceLabel', 'PRICE')}</span><span>${preview('amountLabel', 'AMOUNT (AUD)')}</span></div><div class="tax-invoice-preview__table-row"><span>MacBook Pro 14-inch</span><span>1</span><span>$180.00</span><span>$180.00</span></div><div class="tax-invoice-preview__table-row"><span>Protective case</span><span>1</span><span>$20.00</span><span>$20.00</span></div></div><div class="tax-invoice-preview__summary"><div><span>${preview('subtotalLabel', 'Subtotal')}</span><strong>$200.00</strong></div><div><span>${preview('gstLabel', 'GST')}</span><strong>$18.18</strong></div><div><span>${preview('depositLabel', 'Refundable security deposit')}</span><strong>$100.00</strong></div><div class="tax-invoice-preview__total"><span>${preview('totalLabel', 'TOTAL PAID')}</span><strong>$300.00 AUD</strong></div></div><footer class="tax-invoice-preview__footer"><strong>${preview('thankYouText', 'Thank you for choosing our rental service.')}</strong><span>${preview('recordNote', 'This document records the payment received for the rental order.')}</span><span>${preview('generatedByText', 'Generated by the rental management system')}</span></footer></article></div></div>${script}`
  return buildLayout('Tax Invoice PDF 模板 - 电脑租赁管理系统', body, user)
}
